version: '3.4'

services:
  goitnoderestapi:
    image: goitnoderestapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:3000
