version: '3.4'

services:
  goitnoderestapi:
    image: goitnoderestapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:3000
    command: ["node", "./server.js"]
